import { Actor, HttpAgent } from '@dfinity/agent';

export const useCanister = (canisterName: string) => {
  const agent = new HttpAgent({ host: 'https://ic0.app' }); // Mainnet
  const actor = Actor.createActor<any>(
    // IDL would be generated by dfx; placeholder here
    { service: {} },
    { agent, canisterId: canisterName }
  );

  const call = async (method: string, args: any[] = []) => {
    return actor[method](...args);
  };

  return { call };
};